### ISSUE TITLE
Please correct all mistakes in your book: Clean Code in C# published by Packt.

### ISSUE THREAD

**Issue by lxconan** [PacktPublishing/Clean-Code-in-C-#2]
This is the most ugly book I have ever seen on C#. And you should never buy this book. There are errors on almost every page. Not only the code is so ugly (in a book called clean code), but the content is also ridiculous. Please review the content below:

> In this chapter, we will cover the following topics:
> * Checked and unchecked exceptions
> * Avoiding `NullPointerExceptions`

Pretty good Java book huh? But it is for C#. I have never seen a book like this. Please be professional.

Anyway, please get rid of this. If you really want to learn something on clean code. Please refer to the "Clean Code" written by Robert C·Martin.

**Comment by jasonalls** [comment]
Hi Liu Xia,

Clean Code by Robert C. Martin is geared towards Java programmers. Clean Code in C# is geared towards C# programmers. Two different books, two different authors, two different publishing companies, two different programming languages, with two different audiences.

There is a saying that "You cannot please everyone!" In your cause Lui, it seems you are not happy which is a shame.

However, I do not wish to challenge your professionalism or defend my book called Clean Code in C#. Since we all learn from each other, I am open to your professionalism. And so request that you provide a list of errors that you have found with each page of the book so that these pages can be rectified. And that you also issue a pull request with your version of the code that you deem to be more professional and less ugly.

Kind Regards,

Jason Alls
Author of Clean Code in C#

**Comment by jasonalls** [comment]
Since there has been no further comeback, I am closing this issue.
